### ISSUE TITLE
Webcamoid crashed right after build and run 

### ISSUE THREAD

**Issue by SheerLin** [webcamoid/webcamoid#195] opened 2019-10-04 00:48 UTC
## Summary
Webcamoid crashed right after build and run.

Note: previously I have CamTwist installed on my mac and I thought that's the reason for crashing. But after I uninstall the CamTwist, it is still crashed, so I updated this issue.

## Logs
I have replaced my real path with "[path]" and pasted the logs below:

18:22:10: Starting [path]/webcamoid/StandAlone/debug/Qt5.13.1/clangpp/x86_64/bin/webcamoid --vcam [path]/webcamoid/libAvKys/Plugins/VirtualCamera/src/cmio/VirtualCamera -r -p [path]/webcamoid/libAvKys/Plugins -q [path]/webcamoid/libAvKys...
QML debugging is enabled. Only use this in a safe environment.
[2019-10-03 18:22:11.283, 0x11a03d5c0]  IpcBridge::IpcBridge()
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
18:22:11: The program has unexpectedly finished.
18:22:11: The process was ended forcefully.
18:22:11: [path]/webcamoid/StandAlone/debug/Qt5.13.1/clangpp/x86_64/bin/webcamoid crashed.

## Your Environment
- Webcamoid information: Checked out from last commit bfb3ae84aac968bc7778bf5198dfc632a9aa0adb
- Operating System information: MacOS Mojave 10.14

**Comment by SheerLin** [comment] 2019-10-04 01:07
In Debugger
![image](https://user-images.githubusercontent.com/6592153/66174186-a9898680-e608-11e9-90a2-2b95bee8cbf8.png)

**Comment by SheerLin** [comment] 2019-10-04 01:47
**If I run in Debug mode:**

18:45:58: Debugging starts
QML debugging is enabled. Only use this in a safe environment.
2019-10-03 18:46:03.083256-0700 webcamoid[17520:154868] QML Debugger: Waiting for connection on port 51083...
2019-10-03 18:46:11.115267-0700 webcamoid[17520:154769] [AudioHAL_Client] HALC_ShellObject.cpp:212:HasProperty:  HALC_ShellObject::HasProperty: initial inner method call failed, Error: 560947818 (!obj)
2019-10-03 18:46:11.115296-0700 webcamoid[17520:154769] [AudioHAL_Client] HALC_ShellObject.cpp:212:HasProperty:  HALC_ShellObject::HasProperty: initial inner method call failed, Error: 560947818 (!obj)
2019-10-03 18:46:11.117883-0700 webcamoid[17520:154769] [AudioHAL_Client] HALC_ShellObject.cpp:212:HasProperty:  HALC_ShellObject::HasProperty: initial inner method call failed, Error: 560947818 (!obj)
2019-10-03 18:46:11.117925-0700 webcamoid[17520:154769] [AudioHAL_Client] HALC_ShellObject.cpp:212:HasProperty:  HALC_ShellObject::HasProperty: initial inner method call failed, Error: 560947818 (!obj)
[2019-10-03 18:46:11.234, 0x10029b5c0]  IpcBridge::IpcBridge()
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
18:46:21: Debugging has finished

**Comment by GoEZM** [comment] 2019-10-04 02:07
I also found this problem, the temporary solution is to delete all Webcamoid config files in ~/Library/Preferences.

**Comment by SheerLin** [comment] 2019-10-04 02:50
> I also found this problem, the temporary solution is to delete all Webcamoid config files in ~/Library/Preferences.

Thank you so much! This workaround works! 

But after I open the application, Webcamoid is not connected to my webcam(FaceTime HD Camera). I mean there is the option for FaceTime HD Camera but no streaming displays while the green light of webcam is on. 

Did you experience the same thing after you delete the config files? (Or maybe this is another issue)

**Comment by GoEZM** [comment] 2019-10-04 05:10
The problem is similar to #192, and I have no answer yet.

**Comment by SheerLin** [comment] 2019-10-04 05:12
> The problem is similar to #192, and I have no answer yet.

Thanks!

**Comment by hipersayanX** [comment] 2019-10-06 00:52
Yes I think this is related to #192, here is a [comment update](https://github.com/webcamoid/webcamoid/issues/192#issuecomment-538701406) to the issue.
@SheerLin can you test the [latest build](https://bintray.com/webcamoid/webcamoid/webcamoid/daily#files/mac)?

**Comment by hipersayanX** [comment] 2019-10-25 03:24
Duplicate of #192, closing.

**Closed by hipersayanX** 2019-10-25 03:24 UTC
Labels: Critical: Bug, Platform: Mac, Priority: Hi
