### ISSUE TITLE
virtual background in to do list?

### ISSUE THREAD

**Issue by ahahahaah** [webcamoid/webcamoid#382] opened 2020-12-02 15:32 UTC
hello 
i would like to ask if a virtual background option is or will be in the to do list of this software?
thanks

**Comment by albinscode** [comment] 2020-12-12 17:28
Hi @ahahahaah, please see #250 where the main discussion has started. 
I was interested too in this feature. 

Currently, I've used the last daily built of the 11 of December but got a runtime issue certainly due to dependencies not found on my system. I was able to build it on my own on Ubuntu 20.04 and get rid of some GUI components that were causing trouble. Looks like components related to new GUI currently developed.

By the way, the feature is still not implemented but an interesting one exists. It is to blur what's outside of a "face detection".

![image](https://user-images.githubusercontent.com/8693895/101990527-a4fa3c80-3ca7-11eb-9c68-85652b931051.png)

It can be done on face or other body parts.

![image](https://user-images.githubusercontent.com/8693895/101990559-d5da7180-3ca7-11eb-9848-e522f14e0902.png)


Hope that helps!

**Comment by hipersayanX** [comment] 2020-12-17 14:21
Duplicate of #250, closing.

**Closed by hipersayanX** 2020-12-17 14:21 UTC
Labels: Type: Feature, Verdict: Duplicate
