### ISSUE TITLE
Webcamoid crashing on startup

### ISSUE THREAD

**Issue by nambona890** [webcamoid/webcamoid#173] opened 2019-03-23 11:04 UTC
I downloaded and installed Webcamoid 8.6.0 64-bit, and it crashes not even a second after starting it, straight out of the box. The only thing that shows up when I open it is a window saying "webcamoid has stopped working".
I'm using 64-bit Windows 7.

The crash log:

Problem Event Name:	APPCRASH
  Application Name:	webcamoid.exe
  Application Version:	8.6.0.0
  Application Timestamp:	00000000
  Fault Module Name:	Qt5Cored.dll
  Fault Module Version:	5.12.1.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000602
  Exception Offset:	000000000000f843
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	3081
  Additional Information 1:	fb33
  Additional Information 2:	fb3317dd9ea854a06d33354d2de75885
  Additional Information 3:	abd5
  Additional Information 4:	abd5ed5434f6256bd8c03993227f05ef

**Comment by hipersayanX** [comment] 2019-03-23 22:17
Duplicate of #172.

**Closed by hipersayanX** 2019-03-23 22:17 UTC
Labels: Verdict: Duplicate
