### ISSUE TITLE
Cannot save configuration

### ISSUE THREAD

**Issue by garzaj** [webcamoid/webcamoid#193] opened 2019-09-30 10:20 UTC
Every time I start Webcamoid I have to set all the configurations from scratch. I suppose that should not be the expected behavior. I'm using **Linux Mint 19.1** and used the **Installable 64 bit** version from the homepage. I know this is the same as #150 & #62 , but according to the last comment in #62 this should be working since version 8.6.0 and I'm using 8.6.1

**Comment by hipersayanX** [comment] 2019-09-30 16:05
As said in #62, format, resolution and FPS are saved, every thing else like Brightness, Contrast, Gamma and so on, are not yet. This is more probably related to #190.

**Comment by hipersayanX** [comment] 2019-10-01 12:40
Duplicate of  #190 probably, closing.

**Closed by hipersayanX** 2019-10-01 12:40 UTC
Labels: Verdict: Duplicate
