### ISSUE TITLE
Menu is always visible

### ISSUE THREAD

**Issue by nolfr** [webcamoid/webcamoid#406] opened 2021-02-16 18:14 UTC
First of all, great program, I use it to run my demo's with Webcam #1 and 'my face' on Webcam #2 - both showing on screen, and then shared via Teams, adding also my PPT in the background.
One of the feature questions asked for 'always on top' - this is what I also looked for, but I am now using 'DeskPins' as this is quick and dirty...

Now to my request: can the menu be taken off the visible area of the screen, it can popup when clicked into the screen or on the top bar, but having it always visible is annoing.
...and sorry if this is possible already, and I could not find 'how to'
Thanks

**Comment by hipersayanX** [comment] 2021-02-16 19:21
Duplicate of #203.

**Closed by hipersayanX** 2021-02-16 19:21 UTC
Labels: Type: Feature, Verdict: Duplicate
