### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by shersoni610** [webcamoid/webcamoid#415] opened 2021-03-19 03:26 UTC
Hello,

I get the following errors while compiling on new Mac machine. Can someone help?

src/ak.h:26:7: error: definition of type 'QStringList' conflicts with type alias of the same name
class QStringList;
      ^
/usr/local/Cellar/qt/6.0.2/lib/QtCore.framework/Headers/qcontainerfwd.h:65:7: note: 'QStringList' declared here
using QStringList = QList<QString>;
      ^
src/ak.cpp:140:5: error: use of undeclared identifier 'qRegisterMetaTypeStreamOperators'
    qRegisterMetaTypeStreamOperators<AkCaps>("AkCaps");
    ^
src/ak.cpp:144:5: error: use of undeclared identifier 'qRegisterMetaTypeStreamOperators'
    qRegisterMetaTypeStreamOperators<AkAudioCaps>("AkAudioCaps");
    ^
src/ak.cpp:147:69: error: expected '(' for function-style cast or type construction
    QMetaType::registerDebugStreamOperator<AkAudioCaps::SampleFormat>();
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~^
src/ak.cpp:147:16: error: no member named 'registerDebugStreamOperator' in 'QMetaType'
    QMetaType::registerDebugStreamOperator<AkAudioCaps::SampleFormat>();
    ~~~~~~~~~~~^
src/ak.cpp:147:71: error: expected expression
    QMetaType::registerDebugStreamOperator<AkAudioCaps::SampleFormat>();
                                                                      ^
src/ak.cpp:152:67: error: expected '(' for function-style cast or type construction
    QMetaType::registerDebugStreamOperator<AkAudioCaps::SampleType>();
                                           ~~~~~~~~~~~~~~~~~~~~~~~^
src/ak.cpp:152:16: error: no member named 'registerDebugStreamOperator' in 'QMetaType'
    QMetaType::registerDebugStreamOperator<AkAudioCaps::SampleType>();

**Comment by hipersayanX** [comment] 2021-03-19 15:12
Duplicate of #413, closing.

**Closed by hipersayanX** 2021-03-19 15:12 UTC
Labels: Critical: Bug, Platform: Mac, Verdict: Duplicate
