### ISSUE TITLE
Error adding virtual camera

### ISSUE THREAD

**Issue by BurningCayenne** [webcamoid/webcamoid#338] opened 2020-08-07 00:30 UTC
I'm on Ubuntu 20.04 and I want to create a virtual camera so I can display a looped video to zoom for some upcoming meetings, but when I try to add a virtual camera it gives me an error:

![Screenshot from 2020-08-06 19-26-08 cleaned](https://user-images.githubusercontent.com/33728185/89595662-bd9aa780-d81a-11ea-9912-c1c64d4eacb5.png)

Here is a screenshot of my settings:

![Screenshot from 2020-08-06 19-27-41 cleaned](https://user-images.githubusercontent.com/33728185/89595741-f175cd00-d81a-11ea-870a-b1bf5a9ab744.png)

I've looked at a bunch of the issues posted for this project but none of them helped me with my problem. I'm sure the solution is simple, but I'm not techy enough to get it myself. Any help would be appreciated. Thanks!

**Comment by hipersayanX** [comment] 2020-08-10 22:08
Duplicate of  #296, closing.

**Closed by hipersayanX** 2020-08-10 22:08 UTC
Labels: Critical: Bug, Platform: GNU/Linux, Verdict: Duplicate
