### ISSUE TITLE
Canon DSLR plugin as video input

### ISSUE THREAD

**Issue by cosote** [webcamoid/webcamoid#284] opened 2020-04-20 18:44 UTC
I'd like to share an idea/new feature about adding a plugin to support for Canon DSLR cameras.
My idea was to convert https://sourceforge.net/p/eos-movrec/code/HEAD/tree/trunk/ into a plugin for webcamoid for video input. What about your thoughts?

**Comment by hipersayanX** [comment] 2020-04-24 15:05
Duplicate of #153.

**Closed by hipersayanX** 2020-04-24 15:05 UTC
Labels: Verdict: Duplicate
