### ISSUE TITLE
Webcamoid not starting up, no window showing up.

### ISSUE THREAD

**Issue by LuiCheese** [webcamoid/webcamoid#345] opened 2020-09-02 18:07 UTC
# README

Some considerations before doing anything:

* Search the [issues list](https://github.com/webcamoid/webcamoid/issues) for similar topics before opening a new one.
* If you know how to fix the problem, consider doing a [pull request](https://github.com/webcamoid/webcamoid/pulls) instead of opening a new issue.
* Only report problems in [latest](https://github.com/webcamoid/webcamoid/releases) and [development](https://github.com/webcamoid/webcamoid/) version. Reporting issues related to older versions will be rejected.
* Use [gist](https://gist.github.com/) to post logs longer than 1024 characters.
* Webcamoid as a project, is not affiliated or endorsed to any distribution, report packaging problems in their respective issue tracker.
* Respect the templates, we need as much information as possible.
* Don't open an issue and disappear, we need you at least the first week to clear up missing information.
* Missing information makes useless and unsolvable an issue report.
* You are our debugger, eyes, and hands, if an issue is not reproducible then you will be the only person able to solve it.
* Take a seat and wait for your turn, like many others that have their issues open, or much better try fixing it your self and collaborate with the solution :smile:

Choose one of the templates bellow that fit better your issue.

# Reporting a problem?

## Summary

I start the program by running the .exe and go through the installs fine but when I start the program, even with admin priv. it doesn't show anything but when I hover over the icon it shows a blank window

## Current Behavior

Same as above cant be any more specific

## Expected Behavior

I expected it to start with the UI and allow me to access it.

## Steps to Reproduce

1. Download the latest release for windows
2. Install by running the .exe
3. Start the program

## Suggestions and tips

I guess i would solve it by going through the manual install, but I'm not sure how to do that.

## Your Environment

* Webcamoid information: 8.7.1
* Operating System information: Windows 10
* Any other useful information: 

# Want a new feature?

Id add something here if I could start it :P

# Questions and other matters?

Nope

**Comment by hipersayanX** [comment] 2020-09-03 15:20
Duplicate of #242, closing.

**Closed by hipersayanX** 2020-09-03 15:20 UTC
Labels: Critical: Bug, Platform: Windows, Verdict: Duplicate
