### ISSUE TITLE
Feature request : photo or video background.

### ISSUE THREAD

**Issue by AndKe** [webcamoid/webcamoid#376] opened 2020-11-12 14:45 UTC
In these video conferencing days, many of us are stuck with Micro$oft Teams.
Like all of microsoft, they add some hidden Linux hate where the patent troll minions cant go.
So All "Teams" users know that Linux users have a crippled Teams client with no options for video background.
That said, the microsoft backround is really poor, and works just barely.

**If** webcamoid involved openCV like this: https://elder.dev/posts/open-source-virtual-background/
and even better made video background, (because why not) ?
**Then** it would certainly raise some eyebrows around in companies still stuck in the microsoft world..

**Comment by hipersayanX** [comment] 2020-11-12 16:30
Duplicate of #250.

**Closed by hipersayanX** 2020-11-12 16:30 UTC
Labels: Type: Feature, Verdict: Duplicate
